# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:           /article/:year/:month/:day/:title/
relative_permalinks: false

# Setup
title:            'Leung Enterprises Blog'
tagline:          'Javascript, HTML5, CSS3'
description:      'Lead Web Developer <a href="https://twitter.com/LeungEnterprise">@LeungEnterprise</a>'
baseurl:          /

author:
  name:           'Leung Enterprises'
  url:            http://www.leungenterprises.com/

paginate:         5

# Custom vars
version:          1.1.0


github:           https://github.com/18nleung
linkedin:         https://linkedin.com/in/18nleung
twitter:          https://twitter.com/LeungEnterprise
