# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Nathan Leung
tagline:          'Blog'
description:      'Lead Web Developer <a href="https://twitter.com/LeungEnterprise" target="_blank">@LeungEnterprise</a>'
baseurl:          /

author:
  name:           'Mark Otto'
  url:            https://twitter.com/mdo

paginate:         5

# Custom vars
version:          1.0.0

github:
  repo:           https://github.com/18nleung
